name: Run Selenium Automation

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-automation:
    runs-on: windows-latest  # Ensures it runs on Windows with UI support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install selenium openpyxl pyautogui

      - name: Install Chrome using Chocolatey
        run: |
          choco install googlechrome -y

      - name: Verify Chrome Installation
        run: |
          Get-Command "C:\Program Files\Google\Chrome\Application\chrome.exe"

      - name: Download and setup ChromeDriver
        run: |
          $chromeVersion = (Get-Command "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo.ProductVersion
          $chromeMajorVersion = $chromeVersion.Split('.')[0]
          $latestVersionUrl = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chromeMajorVersion"
          Invoke-WebRequest -Uri $latestVersionUrl -OutFile latest_version.txt
          $latestVersion = Get-Content latest_version.txt
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$latestVersion/chromedriver-win64.zip" -OutFile chromedriver.zip
          Expand-Archive -Path chromedriver.zip -DestinationPath .
          echo "$(pwd)/chromedriver-win64" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

      - name: Verify ChromeDriver Installation
        run: |
          ./chromedriver-win64/chromedriver.exe --version

      - name: Run Selenium Script (Non-Headless Mode)
        run: python script.py
