name: Run Selenium Automation

on:
  # schedule:
  #   - cron: "0 2 * * *"  # Runs every day at 2 AM UTC (Modify as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-automation:
    runs-on: windows-latest  # Non-headless mode requires Windows with UI support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install selenium openpyxl pyautogui

      - name: Download and setup Chrome
        run: |
          curl -o chrome_installer.exe "https://dl.google.com/chrome/install/latest/chrome_installer.exe"
          Start-Process -FilePath chrome_installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait

      - name: Download and setup ChromeDriver
        run: |
          $chromeVersion = (Get-Command "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo.ProductVersion
          $chromeMajorVersion = $chromeVersion.Split('.')[0]
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chromeMajorVersion" -OutFile latest_version.txt
          $latestVersion = Get-Content latest_version.txt
          Invoke-WebRequest -Uri "C://Users//DalalD//Downloads//chromedriver-win64.zip" -OutFile chromedriver.zip
          Expand-Archive -Path chromedriver.zip -DestinationPath .

      - name: Run Selenium Script
        run: python script.py

      - name: Run Selenium script
        env:
          DISPLAY: :99  # Set the display environment variable for GUI
        run: |
          sudo Xvfb :99 -ac &
          python your_script.py  # Replace with the path to your Python script
