name: Run Python Script

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and setup Chrome
        run: |
          curl -o chrome_installer.exe "https://dl.google.com/chrome/install/latest/chrome_installer.exe"
          Start-Process -FilePath chrome_installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait


      - name: Download and setup ChromeDriver
        run: |
          $chromeVersion = (Get-Command "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo.ProductVersion
          $chromeMajorVersion = $chromeVersion.Split('.')[0]
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chromeMajorVersion" -OutFile latest_version.txt
          $latestVersion = Get-Content latest_version.txt
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$latestVersion/chromedriver_win32.zip" -OutFile chromedriver.zip
          Expand-Archive -Path chromedriver.zip -DestinationPath .

      - name: Run Python script
        env:
          DISPLAY: :99  # Set the display environment variable for GUI
        run: |
          sudo Xvfb :99 -ac &
          python your_script.py  # Replace with the path to your Python script
